### ISSUE TITLE
Couldn't jump from search result

### ISSUE THREAD

**Issue by suzukisn** [nlamirault/ripgrep.el#6]
This issue is related to Pull request #5.
When I use ripgrep-regexp command at package 20161008.51, line number displayed in the search result.
However I couldn't jump from search result. I did jump from the search result at package 20160928.9.
This maybe caused by adding the option --vimgrep at package 20161008.51.

When I execute command M-x grep-mode, I can jump from the search result even at package 20161008.51.

**Comment by donatello** [comment]
This happens to me too. I am on repgrep.el `20161008.51` too. When I hit enter on the search result, it just says `No error here` below the mode line.
