### ISSUE TITLE
Add projectile-ripgrep to Melpa

### ISSUE THREAD

**Issue by svend** [nlamirault/ripgrep.el#9]
Thanks for ripgrep.el! Could you add projectile-ripgrep to Melpa as well?

**Comment by nlamirault** [comment]
Yes i will do that asap.

**Comment by nlamirault** [comment]
https://github.com/melpa/melpa/pull/4416

**Comment by nickmccurdy** [comment]
It's on MELPA, this can be closed. Thanks! 😄
